/**
 * Structured slot v1 compatibility fence support (plan 2026-08-14 Task 1).
 *
 * Test-only helpers shared by the six fence test files. Task 1 freezes the
 * v1 baseline BEFORE Contract v2 migration starts: the archived production
 * package bytes (`__fixtures__/zhihu-salt-chapter-v1`) and the generated
 * independent snapshot (`__snapshots__/structured-v1-compatibility.json`)
 * must never change once Task 1 lands. Later tasks migrate the production
 * Zhihu source but must prove the FROZEN v1 digest/hash/Route list/event
 * semantics are unchanged by loading the ARCHIVE and comparing it to the
 * snapshot — the archive, not the production source, is the machine-checked
 * v1 boundary. This module is test-support only; no product module imports
 * it.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { projectStructuredSlotState } from '../storage/structured-slot-state';
import type { TaskEvent } from '../storage/task-events';
import { isStructuredTurnContractV3 } from './template-schema';
import type { FrozenTemplate } from './template-schema';

/** The frozen historical v1 package fixture (byte copy of the production source). */
export const V1_PACKAGE_FIXTURE = fileURLToPath(
  new URL('__fixtures__/zhihu-salt-chapter-v1', import.meta.url),
);

/** The platform-neutral structured fixture whose semantic digest is frozen. */
export const STRUCTURED_VALID_FIXTURE = fileURLToPath(
  new URL('__fixtures__/structured-valid', import.meta.url),
);

/** The committed independent v1 fence snapshot (JSON, generate-once). */
export const V1_SNAPSHOT_FILE = fileURLToPath(
  new URL('__snapshots__/structured-v1-compatibility.json', import.meta.url),
);

/** The deterministic v1 summary projected from a completed acceptance run. */
export interface V1AcceptanceSummary {
  /** The scheduler summary status of the completed v1 run. */
  taskStatus: string;
  /** Projected scaffold structure status ('active' once a generation commits). */
  structureStatus: string;
  /** Projected seal status ('sealed' only via a v1 Seal event). */
  sealStatus: string;
  /** The projected active content revision after all Draft merges. */
  contentRevision: number | null;
  /** Committed `structured_scaffold_generation_committed` events. */
  generationCommitCount: number;
  /** Committed `structured_scaffold_sealed` events. */
  sealEventCount: number;
  /** Committed `final_submission_accepted` events. */
  finalSubmissionCount: number;
  /** Every recorded Draft terminal status, sorted. */
  draftStatuses: string[];
  /** Every recorded Attempt terminal status, sorted. */
  attemptStatuses: string[];
  /** The version of the final artifact the completed run published. */
  finalArtifactVersion: number | null;
}

/** The deterministic loadable v1 surface recorded in the fence snapshot. */
export interface V1TemplateCompatibility {
  /** The archived package's frozen version hash. */
  versionHash: string;
  /** The archived v1 Route list (reachability is load-enforced). */
  routes: FrozenTemplate['routes'];
  /** The closed StructuredTurnContractV3 session union, sorted. */
  v3SessionKinds: string[];
  /** The Contract v1 (FrozenStructuredSlotContractV1) top-level keys, sorted. */
  contractTopLevelKeys: string[];
}

/** The full generated v1 fence snapshot shape. */
export interface V1CompatibilitySnapshot {
  /** Free-text provenance of the generated bytes (never asserted). */
  note: string;
  /** The loaded structured fixture's compiled semantic digest. */
  structuredValidSemanticDigest: string;
  /** The archived Zhihu v1 package's frozen version hash. */
  zhihuV1VersionHash: string;
  /** The archived v1 Route list. */
  zhihuV1Routes: FrozenTemplate['routes'];
  /** Contract v1 top-level keys of the archived package. */
  contractV1TopLevelKeys: string[];
  /** The Closed v3 session union of the archived package's v3 agents. */
  v3SessionUnion: string[];
  /** The projected completed v1 acceptance summary. */
  completedV1AcceptanceSummary: V1AcceptanceSummary;
}

/** Reads the committed fence snapshot; throws when the file is absent. */
export function readV1CompatibilitySnapshot(): V1CompatibilitySnapshot {
  return JSON.parse(readFileSync(V1_SNAPSHOT_FILE, 'utf8')) as V1CompatibilitySnapshot;
}

/**
 * Projects the loadable v1 surface of one frozen template: the frozen version
 * hash, the v1 Route list (an unknown source/target fails the load before any
 * assertion — reachability is Loader-enforced), the closed
 * StructuredTurnContractV3 session union and the Contract v1 top-level keys.
 * Every field feeds the snapshot comparison, so any drift in the archived
 * package bytes changes at least one of them.
 */
export function projectV1TemplateCompatibility(frozen: FrozenTemplate): V1TemplateCompatibility {
  const v3SessionKinds = new Set<string>();
  for (const agent of frozen.agents) {
    if (isStructuredTurnContractV3(agent.turnContract)) {
      v3SessionKinds.add(agent.turnContract.slotSession.kind);
    }
  }
  return {
    versionHash: frozen.versionHash,
    routes: frozen.routes,
    v3SessionKinds: [...v3SessionKinds].sort(),
    contractTopLevelKeys:
      frozen.structuredSlots === null ? [] : Object.keys(frozen.structuredSlots).sort(),
  };
}

/**
 * Projects the completed v1 acceptance summary from the committed event
 * history of one finished v1 run plus the live final artifact version. All
 * fields are deterministic fold results — event ids/timestamps never enter —
 * so the replay result is byte-stable across runs and processes.
 */
export function projectV1AcceptanceSummary(
  events: readonly TaskEvent[],
  taskStatus: string,
  finalArtifactVersion: number | null,
): V1AcceptanceSummary {
  const state = projectStructuredSlotState(events);
  return {
    taskStatus,
    structureStatus: state.structureStatus,
    sealStatus: state.sealStatus,
    contentRevision: state.contentRevision,
    generationCommitCount: events.filter(
      (event) => event.type === 'structured_scaffold_generation_committed',
    ).length,
    sealEventCount: events.filter((event) => event.type === 'structured_scaffold_sealed').length,
    finalSubmissionCount: events.filter((event) => event.type === 'final_submission_accepted')
      .length,
    draftStatuses: Object.values(state.drafts)
      .map((draft) => draft.status)
      .sort(),
    attemptStatuses: Object.values(state.attempts)
      .map((attempt) => attempt.status)
      .sort(),
    finalArtifactVersion,
  };
}

/**
 * A canonical v1 Seal event. The canonical event validator must accept it
 * unchanged (the v2 protocol never widens an existing payload).
 */
export const v1SealEvent = {
  id: 'v1-seal-event',
  at: '2026-08-14T00:00:00.000Z',
  type: 'structured_scaffold_sealed',
  sealId: 'seal-1',
  scaffoldId: 'scaffold-v1',
  generationId: 'generation-v1',
  scaffoldRevision: 1,
  sealRecord: {
    version: 1,
    kind: 'seal_record',
    sha256: 'a'.repeat(64),
    byteLength: 4,
  },
  artifactId: 'chapter',
  artifactVersion: 1,
} as const;